Repository DND-PickMe/pickme-front, pull requests merged in 2020-01, with the labels that each got.

#1 Add: page routing
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/constants/models/routes.js
  src/index.css
  src/index.js
  src/logo.svg
  src/route/auth/SignIn.js
  src/route/auth/SignUp.js
  src/route/main/Main.js
  yarn.lock
Labels: enhancement

#3 Add Appbar
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pickme-front.iml
  .idea/vcs.xml
  .idea/webResources.xml
  package.json
  src/App.js
  src/components/AppBar.js
  src/components/CardWrapper.js
  src/components/Root.js
  src/components/UserInfo.js
  src/constants/models/routes.js
  src/constants/paths.js
  src/index.js
  src/pages/Welcome.js
  src/pages/auth/Profile.js
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
  src/pages/company/Company.js
  src/pages/jobs/Jobs.js
  src/pages/main/Main.js
  src/route/auth/SignIn.js
  src/route/auth/SignUp.js
  src/route/main/Main.js
  yarn.lock
Labels: enhancement

#4 Docs README
  README.md
Labels: Docs

#6 Add Welcome Page, SignIn
  package-lock.json
  src/pages/Welcome.js
  src/pages/auth/SignIn.js
Labels: Add

#8 Refactoring Appbar
  src/App.js
  src/components/AppBar.js
  src/components/Root.js
  src/components/UserInfo.js
Labels: Refactoring
