Repository DND-PickMe/pickme-front, pull requests merged in 2020-02, with the labels that each got.

#11 Fix indent size 4 to 2
  package-lock.json
  package.json
  src/App.js
  src/api/index.js
  src/api/urls.js
  src/components/AppBar.js
  src/components/CardWrapper.js
  src/components/LabelInput.js
  src/components/Root.js
  src/context/AuthContext.js
  src/index.js
  src/pages/Welcome.js
  src/pages/auth/Profile.js
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
  src/pages/enterprise/Enterprise.js
  src/pages/explore/Explore.js
  src/pages/main/Main.js
  src/route/paths.js
Labels: Convention

#12 Add signIn signOut
  .idea/codeStyles/codeStyleConfig.xml
  package.json
  src/App.js
  src/api/index.js
  src/components/AppBar.js
  src/context/AuthContext.js
  src/pages/Welcome.js
  src/pages/auth/AuthCheck.js
  src/pages/auth/SignIn.js
  src/route/PrivateRoute.js
  src/route/paths.js
Labels: Add

#13 Add Resume Page
  src/App.js
  src/components/AppBar.js
  src/pages/resume/Experience.js
  src/pages/resume/License.js
  src/pages/resume/Prize.js
  src/pages/resume/Project.js
  src/pages/resume/Resume.js
  src/pages/resume/SelfInterview.js
  src/pages/resume/UserInfo.js
  src/route/paths.js
Labels: Add

#14 Add signUp
  package-lock.json
  package.json
  src/App.js
  src/api/index.js
  src/api/urls.js
  src/components/AppBar.js
  src/components/CardWrapper.js
  src/components/PasswordInput.js
  src/components/Root.js
  src/index.css
  src/index.js
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
  src/pages/explore/Explore.js
  src/pages/resume/Experience.js
  src/pages/resume/SelfInterview.js
Labels: Add

#16 Add _redirects
  public/_redirects
  public/index.html
  src/pages/main/Main.js
Labels: Fix

#18 Fix post content-type json
  src/App.js
  src/api/index.js
  src/index.css
  src/pages/auth/SignUp.js
  src/pages/enterprise/Enterprise.js
  src/pages/main/Main.js
Labels: Fix

#20 Modify Material-Ui
  src/App.js
  src/components/AppBar.js
  src/pages/Welcome.js
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
  src/route/paths.js
Labels: Fix

#22 AppBar Component를 반응형으로 수정
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pickme-front.iml
  .idea/vcs.xml
  .idea/webResources.xml
  src/components/AppBar.js
  src/pages/Welcome.js
  src/pages/auth/SignIn.js
  src/pages/resume/Resume.js
Labels: Refactoring

#25 Add enterprise signUp
  src/App.js
  src/components/AppBar.js
  src/components/PasswordInput.js
  src/context/AuthContext.js
  src/pages/Welcome.js
  src/pages/auth/AuthCheck.js
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
Labels: Add

#26 Fix SignUp summit
  .gitignore
  package-lock.json
  package.json
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
  yarn.lock
Labels: Fix

#27 Add SignUp with tags
  package.json
  src/App.js
  src/context/AuthContext.js
  src/pages/Welcome.js
  src/pages/auth/SignUp.js
  src/pages/auth/tagsinput.css
  src/pages/explore/Explore.js
  src/pages/main/Main.js
  src/pages/resume/Experience.js
  src/pages/resume/License.js
  src/pages/resume/Prize.js
  src/pages/resume/Project.js
  src/pages/resume/Resume.js
  src/pages/resume/SelfInterview.js
  src/pages/resume/UserInfo.js
Labels: Add

#28 Add sweetalert2
  package-lock.json
  package.json
  src/components/AppBar.js
  src/components/PasswordInput.js
  src/index.css
  src/pages/auth/SignIn.js
  src/pages/auth/SignUp.js
  src/pages/main/Main.js
  src/pages/resume/Resume.js
Labels: Add

#29 Add Profile page
  src/api/index.js
  src/pages/auth/Profile.js
  src/pages/auth/SignUp.js
  src/pages/resume/Resume.js
Labels: Add

#33 Add modify carrer, position
  package-lock.json
  package.json
  src/App.js
  src/components/AppBar.js
  src/constants/values.js
  src/pages/auth/Profile.js
  src/pages/auth/SignIn.js
  src/pages/auth/tags.css
  src/pages/auth/tagsinput.css
  src/pages/main/Main.js
  src/pages/resume/AddResume.js
  src/pages/resume/Resume.js
  src/route/paths.js
Labels: Add
